In [1]:
import numpy as np

In [2]:
Ts = np.array([[1, 0, 0, 5],
               [0, 1, 0, 4],
               [0, 0, 1, 3],
               [0, 0, 0, 1]])

Tp = np.array([[1, 0, 0, 3],
               [0, 1, 0, 4],
               [0, 0, 1, 5],
               [0, 0, 0, 1]])

pose = np.linalg.inv(np.dot(Tp, np.linalg.inv(Ts)))
print(pose)

[[ 1.  0.  0.  2.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1. -2.]
 [ 0.  0.  0.  1.]]


In [3]:
Ts = np.array([[1, 0, 0, 0.5],
               [0, 1, 0, 0.4],
               [0, 0, 1, 0.3],
               [0, 0, 0, 1]])

Tp = np.array([[1, 0, 0, 0.3],
               [0, 1, 0, 0.4],
               [0, 0, 1, 0.5],
               [0, 0, 0, 1]])

pose = np.linalg.inv(np.dot(Tp, np.linalg.inv(Ts)))
print(pose)

[[ 1.   0.   0.   0.2]
 [ 0.   1.   0.   0. ]
 [ 0.   0.   1.  -0.2]
 [ 0.   0.   0.   1. ]]


T矩阵不具有尺度不变性